name: golangci-lint
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  GOGC: 50

jobs:
  golangci:
    name: lint
    runs-on: arc-runner-set-na
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go get .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=60m
